# Generated by Django 6.0.4 on 2026-04-07 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(db_collation='nocase', unique=True)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(db_collation='nocase', unique=True)),
            ],
            options={
                'db_table': 'topics',
            },
        ),
        migrations.CreateModel(
            name='Hymn',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('verse', models.TextField(blank=True, null=True)),
                ('has_track', models.IntegerField(default=0)),
                ('has_demo', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hymns.author')),
                ('topics', models.ManyToManyField(blank=True, db_table='hymn_topics', related_name='hymns', to='hymns.topic')),
            ],
            options={
                'db_table': 'hymns',
            },
        ),
        migrations.CreateModel(
            name='HymnTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField()),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('hymn', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hymns.hymn')),
            ],
            options={
                'db_table': 'hymn_translations',
                'constraints': [models.UniqueConstraint(fields=('hymn', 'language'), name='hymn_language_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='hymn',
            constraint=models.CheckConstraint(condition=models.Q(('has_demo__in', [0, 1])), name='hymns_has_demo_0_1'),
        ),
        migrations.AddConstraint(
            model_name='hymn',
            constraint=models.CheckConstraint(condition=models.Q(('has_track__in', [0, 1])), name='hymns_has_track_0_1'),
        ),
    ]
