import { Hymn } from '~/types/hymn';

export const hymns: Hymn[] = [
  {
    id: 1,
    title: 'Amazing Grace',
    text: 'Amazing Grace, how sweet the sound...',
    verse: 'John 3:16',
    author_name: 'John Newton',
    has_track: true,
    has_demo: false,
    is_favorite: false,
  },
  {
    id: 2,
    title: 'How Great Thou Art',
    verse: 'Psalm 8:1',
    author_name: 'Carl Boberg',
    text: 'O Lord my God, when I in awesome wonder...',
    has_track: false,
    has_demo: true,
    is_favorite: true,
  },
  {
    id: 3,
    title: 'Be Thou My Vision',
    verse: 'Proverbs 3:5-6',
    author_name: 'Dallan Forgaill',
    text: 'Be Thou my vision, O Lord of my heart...',
    has_track: true,
    has_demo: true,
    is_favorite: false,
  },
  {
    id: 4,
    title: 'It Is Well With My Soul',
    verse: 'Philippians 4:7',
    author_name: 'Horatio Spafford',
    text: 'When peace like a river, attendeth my way...',
    has_track: false,
    has_demo: false,
    is_favorite: true,
  },
  {
    id: 5,
    title: 'Great Is Thy Faithfulness',
    verse: 'Lamentations 3:22-23',
    author_name: 'Thomas Chisholm',
    text: 'Great is Thy faithfulness, O God my Father...',
    has_track: true,
    has_demo: false,
    is_favorite: false,
  },
  {
    id: 6,
    title: 'Holy, Holy, Holy',
    verse: 'Isaiah 6:3',
    author_name: 'Reginald Heber',
    text: 'Holy, holy, holy! Lord God Almighty!',
    has_track: true,
    has_demo: true,
    is_favorite: true,
  },
  {
    id: 7,
    title: 'Blessed Assurance',
    verse: '1 John 5:13',
    author_name: 'Fanny J. Crosby',
    text: 'Blessed assurance, Jesus is mine!',
    has_track: false,
    has_demo: true,
    is_favorite: false,
  },
];
